<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="property" nsURI="http://www.eclipse.gemoc.org/property" nsPrefix="property">
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.viatra.query.patternlanguage.emf/model/PatternLanguage.ecore#//Pattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantifiedProperty" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" lowerBound="1"
        eType="#//Quantifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalProperty" abstract="true" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1" eType="#//Scope"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPLProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statement" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.viatra.query.patternlanguage.emf/model/PatternLanguage.ecore#//Pattern"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialTruthValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Absence" eSuperTypes="#//TemporalProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Universality" eSuperTypes="#//TemporalProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Existence" eSuperTypes="#//TemporalProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedTemporalProperty" abstract="true"
      eSuperTypes="#//TemporalProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherPattern" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.viatra.query.patternlanguage.emf/model/PatternLanguage.ecore#//Pattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response" eSuperTypes="#//OrderedTemporalProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Precedence" eSuperTypes="#//OrderedTemporalProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Globally" eSuperTypes="#//Scope"/>
  <eClassifiers xsi:type="ecore:EClass" name="LowerBounded" abstract="true" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBoundPattern" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.viatra.query.patternlanguage.emf/model/PatternLanguage.ecore#//Pattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpperBounded" abstract="true" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBoundPattern" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.viatra.query.patternlanguage.emf/model/PatternLanguage.ecore#//Pattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Before" eSuperTypes="#//UpperBounded"/>
  <eClassifiers xsi:type="ecore:EClass" name="Between" eSuperTypes="#//LowerBounded #//UpperBounded"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfterUntil" eSuperTypes="#//LowerBounded #//UpperBounded"/>
  <eClassifiers xsi:type="ecore:EClass" name="After" eSuperTypes="#//LowerBounded"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Quantifier">
    <eLiterals name="FORALL"/>
    <eLiterals name="EXISTS" value="1"/>
  </eClassifiers>
</ecore:EPackage>
